apiVersion: v1
kind: Service
metadata:
  name: fib-service
spec:
  selector:
    app: fib-app
  ports:
    - protocol: "TCP"
      port: 6000
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fib-app
spec:
  selector:
    matchLabels:
      app: fib-app
  replicas: 1
  template:
    metadata:
      labels:
        app: fib-app
    spec:
      containers:
        - name: fib-app
          image: fibonacchi-app:v2
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
