apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: openfaas-latency
  namespace: chaos-mesh
spec:
  action: delay
  mode: all
  selector:
    labelSelectors:
      'faas_function': 'figlet'
    namespaces:
      - openfaas-fn
  delay:
    latency: '50ms'
    correlation: '100'
    jitter: '0ms'
  duration: '1m'
